site_name: Fundamentos de Redes de Computadores
copyright: 2023 Nicolas Souza
repo_name: REDES-notes
repo_url: https://github.com/nszchagas/REDES-notes

theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: material/book-outline
    repo: fontawesome/brands/github
  features:
    - toc.follow
    - navigation.expand
  palette:
    - scheme: default
      primary: blue grey

extra_css:
  - assets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Início: index.md
  - HTTP: http.md