site_name: Fundamentos de Redes de Computadores
copyright: 2023 Nicolas Souza
repo_name: REDES-notes
repo_url: https://github.com/nszchagas/REDES-notes

theme:
  name: material
  logo: assets/icon.png
  features:
    - content.code.annotate
    - content.code.copy
    - toc.integrate
  favicon: assets/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: \033[0;34mindigo\033[0m
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: \033[0;34mindigo\033[0m
      toggle:
        icon: material/brightness-4
        name: Light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["codes"]
  - pymdownx.superfences
  - attr_list

nav:
  - Início: index.md
