#!/bin/bash

function config_ip() {

    netmask=$1
    my_ip=$2
    i_name=$3
    broadcast=$4

    interface="$(ifconfig | grep "$i_name" | awk -F ':' '{print $1}')"
    echo "Atribuindo endereço IP=$my_ip e netmask=$netmask para a interface de rede $interface"
    ifconfig $interface $my_ip netmask $netmask || return 1

}

function config_network() {

    netmask="255.255.255.0"
    ip_usb="192.168.3.3"
    i_name="enx"
    broadcast="192.168.333.255"
    echo "Configurando o roteador (máquina atual) na interface USB (enx00e04c534458) na primeira rede: $my_ip"
    config_ip $netmask $ip_usb $i_name $broadcast

    netmask="255.255.255.0"
    ip_et="192.168.1.1"
    i_name="enp"
    broadcast="192.168.333.255"
    echo "Configurando o roteador (máquina atual) na interface Ethernet (enp1s0) em outra rede: $my_ip"
    config_ip $netmask $ip_et $i_name $broadcast

}

echo "Parando o serviço automático de rede"
sudo service networking stop || {
    exit 1
    echo "Falha ao parar serviço"
}

echo "Enable ip forwarding"
sudo sysctl -w net.ipv4.ip_forward=1
config_network

echo "Configurando rede entre roteador e enp1"
ifconfig enp1s0 192.168.3.2 netmask 255.255.255.255 broadcast 192.168.3.255

echo "Teste local: ping 192.168.3.2"
ping 192.168.3.2

echo "Habilitando rota para $ip_et pelo link enp1s0"
route add -net 192.168.3.0 netmask 255.255.255.0 enp1s0
