#!/bin/bash

# Curl flags: --include: Inclui o header da resposta na saída.
cmd="curl --include --http1.1 -X GET http://nginx"
echo "Testando HTTP/1.1 com o comando curl ($cmd):"
resultado="$($cmd)"
echo -e "Resultado:\n$resultado\n"


# A flag --insecure é passada para que o curl não verifique os certificados ssl (o usado é self-signed).
cmd="curl --include --http2 -X GET --insecure https://nginx"
echo "Testando HTTP/2 com o comando curl ($cmd):"
resultado="$($cmd)"
echo -e "Resultado:\n$resultado\n"

cmd="curl --include --http3 -X GET --insecure https://nginx"
echo "Testando HTTP/3 com o comando curl ($cmd):"
resultado="$($cmd)"
echo -e "Resultado:\n$resultado\n"
